// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"strings"

	"github.com/ysugimoto/falco/v2/interpreter/context"
	"github.com/ysugimoto/falco/v2/interpreter/function/errors"
	"github.com/ysugimoto/falco/v2/interpreter/function/shared"
	"github.com/ysugimoto/falco/v2/interpreter/value"
)

const Querystring_sort_Name = "querystring.sort"

// Fastly returns the URL untouched once its query string holds this many
// parameters, so neither the sort nor only_unique_keys is applied. Empty
// parameters count toward the limit.
const Querystring_sort_ParameterLimit = 32

var Querystring_sort_ArgumentTypes = []value.Type{value.StringType, value.BooleanType}

func Querystring_sort_Validate(args []value.Value) error {
	if len(args) < 1 || len(args) > 2 {
		return errors.ArgumentNotInRange(Querystring_sort_Name, 1, 2, args)
	}
	for i := range args {
		if args[i].Type() != Querystring_sort_ArgumentTypes[i] {
			return errors.TypeMismatch(Querystring_sort_Name, i+1, Querystring_sort_ArgumentTypes[i], args[i].Type())
		}
	}
	return nil
}

// Fastly built-in function implementation of querystring.sort
// Arguments may be:
// - STRING, BOOL
// - STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/query-string/querystring-sort/
func Querystring_sort(ctx *context.Context, args ...value.Value) (value.Value, error) {
	// Argument validations
	if err := Querystring_sort_Validate(args); err != nil {
		return value.Null, err
	}

	u := value.Unwrap[*value.String](args[0])

	if idx := strings.Index(u.Value, "?"); idx != -1 {
		if strings.Count(u.Value[idx+1:], "&")+1 >= Querystring_sort_ParameterLimit {
			return &value.String{Value: u.Value}, nil
		}
	}

	query, err := shared.ParseQuery(u.Value)
	if err != nil {
		return value.Null, errors.New(
			Querystring_sort_Name, "Failed to parse urquery: %s, error: %s", u.Value, err.Error(),
		)
	}

	// The optional only_unique_keys argument filters out repeated keys.
	// Fastly keeps the first occurrence in input order, so this must run
	// before sorting.
	if len(args) > 1 && value.Unwrap[*value.Boolean](args[1]).Value {
		query.Unique()
	}

	query.Sort(shared.SortAsc)
	return &value.String{Value: query.String()}, nil
}
